---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Fix Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          target: graalvm.json

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: graalvm.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          target: graalvm.json
